 -- MySQL Script generated by MySQL Workbench
-- Thu Jun  2 13:08:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produtos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produtos` (
  `idprodutos` INT NOT NULL,
  `produtoscol` VARCHAR(45) NOT NULL,
  `produtoscol1` VARCHAR(45) NULL,
  `produtos_idprodutos` INT NOT NULL,
  PRIMARY KEY (`idprodutos`, `produtoscol`),
  INDEX `fk_produtos_produtos1_idx` (`produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `mydb`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nota fiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nota fiscal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nota fiscal` (
  `idnota fiscal` INT NOT NULL,
  `nota fiscalcol` VARCHAR(45) NULL,
  `nota fiscalcol1` VARCHAR(45) NULL,
  `nota fiscalcol2` VARCHAR(45) NULL,
  `nota fiscalcol3` VARCHAR(45) NULL,
  `nota fiscalcol4` VARCHAR(45) NOT NULL,
  `nota fiscalcol5` VARCHAR(45) NOT NULL,
  `nota fiscalcol6` VARCHAR(45) NOT NULL,
  `nota fiscalcol7` VARCHAR(45) NOT NULL,
  `nota fiscalcol8` VARCHAR(45) NOT NULL,
  `produtos_idprodutos` INT NOT NULL,
  PRIMARY KEY (`idnota fiscal`, `nota fiscalcol6`, `nota fiscalcol7`, `nota fiscalcol8`),
  INDEX `fk_nota fiscal_produtos1_idx` (`produtos_idprodutos` ASC) VISIBLE,
  CONSTRAINT `fk_nota fiscal_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `mydb`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `idpedidos` INT NOT NULL,
  `nota fiscal_idnota fiscal` INT NOT NULL,
  `nota fiscal_idnota fiscal1` INT NOT NULL,
  `nota fiscal_nota fiscalcol` VARCHAR(45) NOT NULL,
  `nota fiscal_nota fiscalcol1` VARCHAR(45) NOT NULL,
  `nota fiscal_nota fiscalcol6` VARCHAR(45) NOT NULL,
  `nota fiscal_nota fiscalcol7` VARCHAR(45) NOT NULL,
  `nota fiscal_nota fiscalcol8` VARCHAR(45) NOT NULL,
  INDEX `fk_pedidos_nota fiscal_idx` (`nota fiscal_idnota fiscal` ASC) VISIBLE,
  INDEX `fk_pedidos_nota fiscal1_idx` (`nota fiscal_idnota fiscal1` ASC, `nota fiscal_nota fiscalcol` ASC, `nota fiscal_nota fiscalcol1` ASC, `nota fiscal_nota fiscalcol6` ASC, `nota fiscal_nota fiscalcol7` ASC, `nota fiscal_nota fiscalcol8` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_nota fiscal`
    FOREIGN KEY (`nota fiscal_idnota fiscal`)
    REFERENCES `mydb`.`nota fiscal` (`idnota fiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_nota fiscal1`
    FOREIGN KEY (`nota fiscal_idnota fiscal1` , `nota fiscal_nota fiscalcol` , `nota fiscal_nota fiscalcol1` , `nota fiscal_nota fiscalcol6` , `nota fiscal_nota fiscalcol7` , `nota fiscal_nota fiscalcol8`)
    REFERENCES `mydb`.`nota fiscal` (`idnota fiscal` , `nota fiscalcol` , `nota fiscalcol1` , `nota fiscalcol6` , `nota fiscalcol7` , `nota fiscalcol8`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
